apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-docker
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sh", "-c", "apt-get update && apt-get install -y docker.io && sleep infinity"]
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
    securityContext:
      privileged: true
    env:
    - name: DEBIAN_FRONTEND
      value: noninteractive
    - name: TZ
      value: "UTC"
    - name: LANG
      value: "en_US.UTF-8"
    - name: LANGUAGE
      value: "en_US.UTF-8"
    - name: LC_ALL
      value: "en_US.UTF-8"
  volumes:
  - name: docker-socket
    hostPath:
      path: /run/docker.sock
      type: Socket